FROM python:3.9 as build

WORKDIR /app

COPY . /app

# Setze die Umgebungsvariablen
ENV MODBUS_IP=192.168.1.231
ENV MODBUS_PORT=5743
ENV MODBUS_SLAVE=252
ENV MODBUS_TIMEOUT=5
ENV MODBUS_RETRIES=3
ENV MODBUS_FRAMER="rtu"

ENV MQTT_DISABLE=False
ENV MQTT_SERVER=192.168.1.123
ENV MQTT_PORT=1883
ENV MQTT_LOGIN="MQTT"
ENV MQTT_PASSWORD="MQTT"
ENV MQTT_TOPIC=MTEC
ENV MQTT_FLOAT_FORMAT="{:.3f}"

ENV REFRESH_NOW_S=10
ENV REFRESH_NOWEXT_S=30
ENV REFRESH_DAY_M=5
ENV REFRESH_TOTAL_M=5
ENV REFRESH_CONFIG_M=60

ENV ENABLE_GRID_DATA=False
ENV ENABLE_INVERTER_DATA=False
ENV ENABLE_BACKUP_DATA=False
ENV ENABLE_BATTERY_DATA=False
ENV ENABLE_PV_DATA=False

ENV HASS_ENABLE=False
ENV HASS_BASE_TOPIC=homeassistant
ENV HASS_BIRTH_GRACETIME=15

ENV DEBUG=False

EXPOSE 5743
EXPOSE 1883

RUN pip3 install -r requirements.txt

CMD [ "python", "mtec_mqtt.py" ]